-- MySQL Script generated by MySQL Workbench
-- jue 21 dic 2017 09:22:05 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica` ;

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica` DEFAULT CHARACTER SET latin1 ;
USE `clinica` ;

-- -----------------------------------------------------
-- Table `clinica`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` INT(9) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `clinica`.`usuarios` (`id_usuario` ASC);

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `clinica`.`usuarios` (`user` ASC);
CREATE UNIQUE INDEX `password_UNIQUE` ON `clinica`.`usuarios` (`password` ASC);

INSERT INTO `clinica`.`usuarios` (`id_usuario`, `nombre`, `apellidos`, `telefono`, `user`, `password`, `tipo`) 
VALUES ('1', 'Pepe', 'Gallego', '123456789', 'admin', 'admin', 'admin');

-- -----------------------------------------------------
-- Table `clinica`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`citas` (
  `numero` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `hora` time NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`numero`, `id_usuario`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `clinica`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `numero_UNIQUE` ON `clinica`.`citas` (`numero` ASC);

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `clinica`.`citas` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`empleados` (
  `id_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` INT(9) NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `id_empleado_UNIQUE` ON `clinica`.`empleados` (`id_empleado` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`facturas` (
  `id_factura` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `numero` INT(11) NOT NULL,
  PRIMARY KEY (`id_factura`, `numero`),
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `clinica`.`citas` (`numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `idfacturas_UNIQUE` ON `clinica`.`facturas` (`id_factura` ASC);

CREATE UNIQUE INDEX `numero_UNIQUE` ON `clinica`.`facturas` (`numero` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`atender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`atender` (
  `id_atender` INT NOT NULL AUTO_INCREMENT,
  `numero_cita` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_atender`),
  CONSTRAINT 
    FOREIGN KEY (`numero_cita`)
    REFERENCES `clinica`.`citas` (`numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT 
    FOREIGN KEY (`id_empleado`)
    REFERENCES `clinica`.`empleados` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_atender_UNIQUE` ON `clinica`.`atender` (`id_atender` ASC);

CREATE UNIQUE INDEX `numero_UNIQUE` ON `clinica`.`atender` (`numero_cita` ASC);

CREATE UNIQUE INDEX `id_empleado_UNIQUE` ON `clinica`.`atender` (`id_empleado` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
